// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _Ascii85Info {
 *     long offset;
 *     long line_break;
 *     magick_uint8_t buffer[10];
 * }
 * }
 */
public class _Ascii85Info {

    _Ascii85Info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        magick_wand_h.C_LONG.withName("offset"),
        magick_wand_h.C_LONG.withName("line_break"),
        MemoryLayout.sequenceLayout(10, magick_wand_h.C_CHAR).withName("buffer"),
        MemoryLayout.paddingLayout(6)
    ).withName("_Ascii85Info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long offset
     * }
     */
    public static final OfLong offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long offset
     * }
     */
    public static long offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long offset
     * }
     */
    public static void offset(MemorySegment struct, long fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    private static final OfLong line_break$LAYOUT = (OfLong)$LAYOUT.select(groupElement("line_break"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long line_break
     * }
     */
    public static final OfLong line_break$layout() {
        return line_break$LAYOUT;
    }

    private static final long line_break$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long line_break
     * }
     */
    public static final long line_break$offset() {
        return line_break$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long line_break
     * }
     */
    public static long line_break(MemorySegment struct) {
        return struct.get(line_break$LAYOUT, line_break$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long line_break
     * }
     */
    public static void line_break(MemorySegment struct, long fieldValue) {
        struct.set(line_break$LAYOUT, line_break$OFFSET, fieldValue);
    }

    private static final SequenceLayout buffer$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static final SequenceLayout buffer$layout() {
        return buffer$LAYOUT;
    }

    private static final long buffer$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static final long buffer$offset() {
        return buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static MemorySegment buffer(MemorySegment struct) {
        return struct.asSlice(buffer$OFFSET, buffer$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static void buffer(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, buffer$OFFSET, buffer$LAYOUT.byteSize());
    }

    private static long[] buffer$DIMS = { 10 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static long[] buffer$dimensions() {
        return buffer$DIMS;
    }
    private static final VarHandle buffer$ELEM_HANDLE = buffer$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static byte buffer(MemorySegment struct, long index0) {
        return (byte)buffer$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * magick_uint8_t buffer[10]
     * }
     */
    public static void buffer(MemorySegment struct, long index0, byte fieldValue) {
        buffer$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

