// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _CompositeOptions_t {
 *     double percent_brightness;
 *     double amount;
 *     double threshold;
 * }
 * }
 */
public class _CompositeOptions_t {

    _CompositeOptions_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        magick_wand_h.C_DOUBLE.withName("percent_brightness"),
        magick_wand_h.C_DOUBLE.withName("amount"),
        magick_wand_h.C_DOUBLE.withName("threshold")
    ).withName("_CompositeOptions_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble percent_brightness$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("percent_brightness"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double percent_brightness
     * }
     */
    public static final OfDouble percent_brightness$layout() {
        return percent_brightness$LAYOUT;
    }

    private static final long percent_brightness$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double percent_brightness
     * }
     */
    public static final long percent_brightness$offset() {
        return percent_brightness$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double percent_brightness
     * }
     */
    public static double percent_brightness(MemorySegment struct) {
        return struct.get(percent_brightness$LAYOUT, percent_brightness$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double percent_brightness
     * }
     */
    public static void percent_brightness(MemorySegment struct, double fieldValue) {
        struct.set(percent_brightness$LAYOUT, percent_brightness$OFFSET, fieldValue);
    }

    private static final OfDouble amount$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("amount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double amount
     * }
     */
    public static final OfDouble amount$layout() {
        return amount$LAYOUT;
    }

    private static final long amount$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double amount
     * }
     */
    public static final long amount$offset() {
        return amount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double amount
     * }
     */
    public static double amount(MemorySegment struct) {
        return struct.get(amount$LAYOUT, amount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double amount
     * }
     */
    public static void amount(MemorySegment struct, double fieldValue) {
        struct.set(amount$LAYOUT, amount$OFFSET, fieldValue);
    }

    private static final OfDouble threshold$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("threshold"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double threshold
     * }
     */
    public static final OfDouble threshold$layout() {
        return threshold$LAYOUT;
    }

    private static final long threshold$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double threshold
     * }
     */
    public static final long threshold$offset() {
        return threshold$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double threshold
     * }
     */
    public static double threshold(MemorySegment struct) {
        return struct.get(threshold$LAYOUT, threshold$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double threshold
     * }
     */
    public static void threshold(MemorySegment struct, double fieldValue) {
        struct.set(threshold$LAYOUT, threshold$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

