// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _DifferenceImageOptions {
 *     ChannelType channel;
 *     HighlightStyle highlight_style;
 *     PixelPacket highlight_color;
 * }
 * }
 */
public class _DifferenceImageOptions {

    _DifferenceImageOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        magick_wand_h.C_INT.withName("channel"),
        magick_wand_h.C_INT.withName("highlight_style"),
        _PixelPacket.layout().withName("highlight_color")
    ).withName("_DifferenceImageOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt channel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("channel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ChannelType channel
     * }
     */
    public static final OfInt channel$layout() {
        return channel$LAYOUT;
    }

    private static final long channel$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ChannelType channel
     * }
     */
    public static final long channel$offset() {
        return channel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ChannelType channel
     * }
     */
    public static int channel(MemorySegment struct) {
        return struct.get(channel$LAYOUT, channel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ChannelType channel
     * }
     */
    public static void channel(MemorySegment struct, int fieldValue) {
        struct.set(channel$LAYOUT, channel$OFFSET, fieldValue);
    }

    private static final OfInt highlight_style$LAYOUT = (OfInt)$LAYOUT.select(groupElement("highlight_style"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighlightStyle highlight_style
     * }
     */
    public static final OfInt highlight_style$layout() {
        return highlight_style$LAYOUT;
    }

    private static final long highlight_style$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighlightStyle highlight_style
     * }
     */
    public static final long highlight_style$offset() {
        return highlight_style$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighlightStyle highlight_style
     * }
     */
    public static int highlight_style(MemorySegment struct) {
        return struct.get(highlight_style$LAYOUT, highlight_style$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighlightStyle highlight_style
     * }
     */
    public static void highlight_style(MemorySegment struct, int fieldValue) {
        struct.set(highlight_style$LAYOUT, highlight_style$OFFSET, fieldValue);
    }

    private static final GroupLayout highlight_color$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("highlight_color"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PixelPacket highlight_color
     * }
     */
    public static final GroupLayout highlight_color$layout() {
        return highlight_color$LAYOUT;
    }

    private static final long highlight_color$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PixelPacket highlight_color
     * }
     */
    public static final long highlight_color$offset() {
        return highlight_color$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PixelPacket highlight_color
     * }
     */
    public static MemorySegment highlight_color(MemorySegment struct) {
        return struct.asSlice(highlight_color$OFFSET, highlight_color$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PixelPacket highlight_color
     * }
     */
    public static void highlight_color(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, highlight_color$OFFSET, highlight_color$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

