// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _ErrorInfo {
 *     double mean_error_per_pixel;
 *     double normalized_mean_error;
 *     double normalized_maximum_error;
 * }
 * }
 */
public class _ErrorInfo {

    _ErrorInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        magick_wand_h.C_DOUBLE.withName("mean_error_per_pixel"),
        magick_wand_h.C_DOUBLE.withName("normalized_mean_error"),
        magick_wand_h.C_DOUBLE.withName("normalized_maximum_error")
    ).withName("_ErrorInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble mean_error_per_pixel$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mean_error_per_pixel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mean_error_per_pixel
     * }
     */
    public static final OfDouble mean_error_per_pixel$layout() {
        return mean_error_per_pixel$LAYOUT;
    }

    private static final long mean_error_per_pixel$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mean_error_per_pixel
     * }
     */
    public static final long mean_error_per_pixel$offset() {
        return mean_error_per_pixel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mean_error_per_pixel
     * }
     */
    public static double mean_error_per_pixel(MemorySegment struct) {
        return struct.get(mean_error_per_pixel$LAYOUT, mean_error_per_pixel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mean_error_per_pixel
     * }
     */
    public static void mean_error_per_pixel(MemorySegment struct, double fieldValue) {
        struct.set(mean_error_per_pixel$LAYOUT, mean_error_per_pixel$OFFSET, fieldValue);
    }

    private static final OfDouble normalized_mean_error$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("normalized_mean_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double normalized_mean_error
     * }
     */
    public static final OfDouble normalized_mean_error$layout() {
        return normalized_mean_error$LAYOUT;
    }

    private static final long normalized_mean_error$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double normalized_mean_error
     * }
     */
    public static final long normalized_mean_error$offset() {
        return normalized_mean_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double normalized_mean_error
     * }
     */
    public static double normalized_mean_error(MemorySegment struct) {
        return struct.get(normalized_mean_error$LAYOUT, normalized_mean_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double normalized_mean_error
     * }
     */
    public static void normalized_mean_error(MemorySegment struct, double fieldValue) {
        struct.set(normalized_mean_error$LAYOUT, normalized_mean_error$OFFSET, fieldValue);
    }

    private static final OfDouble normalized_maximum_error$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("normalized_maximum_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double normalized_maximum_error
     * }
     */
    public static final OfDouble normalized_maximum_error$layout() {
        return normalized_maximum_error$LAYOUT;
    }

    private static final long normalized_maximum_error$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double normalized_maximum_error
     * }
     */
    public static final long normalized_maximum_error$offset() {
        return normalized_maximum_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double normalized_maximum_error
     * }
     */
    public static double normalized_maximum_error(MemorySegment struct) {
        return struct.get(normalized_maximum_error$LAYOUT, normalized_maximum_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double normalized_maximum_error
     * }
     */
    public static void normalized_maximum_error(MemorySegment struct, double fieldValue) {
        struct.set(normalized_maximum_error$LAYOUT, normalized_maximum_error$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

