// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _ExportPixelAreaInfo {
 *     size_t bytes_exported;
 * }
 * }
 */
public class _ExportPixelAreaInfo {

    _ExportPixelAreaInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        magick_wand_h.C_LONG.withName("bytes_exported")
    ).withName("_ExportPixelAreaInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong bytes_exported$LAYOUT = (OfLong)$LAYOUT.select(groupElement("bytes_exported"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t bytes_exported
     * }
     */
    public static final OfLong bytes_exported$layout() {
        return bytes_exported$LAYOUT;
    }

    private static final long bytes_exported$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t bytes_exported
     * }
     */
    public static final long bytes_exported$offset() {
        return bytes_exported$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t bytes_exported
     * }
     */
    public static long bytes_exported(MemorySegment struct) {
        return struct.get(bytes_exported$LAYOUT, bytes_exported$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t bytes_exported
     * }
     */
    public static void bytes_exported(MemorySegment struct, long fieldValue) {
        struct.set(bytes_exported$LAYOUT, bytes_exported$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

