// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _ImageStatistics {
 *     ImageChannelStatistics red;
 *     ImageChannelStatistics green;
 *     ImageChannelStatistics blue;
 *     ImageChannelStatistics opacity;
 * }
 * }
 */
public class _ImageStatistics {

    _ImageStatistics() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _ImageChannelStatistics.layout().withName("red"),
        _ImageChannelStatistics.layout().withName("green"),
        _ImageChannelStatistics.layout().withName("blue"),
        _ImageChannelStatistics.layout().withName("opacity")
    ).withName("_ImageStatistics");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout red$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("red"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImageChannelStatistics red
     * }
     */
    public static final GroupLayout red$layout() {
        return red$LAYOUT;
    }

    private static final long red$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImageChannelStatistics red
     * }
     */
    public static final long red$offset() {
        return red$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics red
     * }
     */
    public static MemorySegment red(MemorySegment struct) {
        return struct.asSlice(red$OFFSET, red$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics red
     * }
     */
    public static void red(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, red$OFFSET, red$LAYOUT.byteSize());
    }

    private static final GroupLayout green$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("green"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImageChannelStatistics green
     * }
     */
    public static final GroupLayout green$layout() {
        return green$LAYOUT;
    }

    private static final long green$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImageChannelStatistics green
     * }
     */
    public static final long green$offset() {
        return green$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics green
     * }
     */
    public static MemorySegment green(MemorySegment struct) {
        return struct.asSlice(green$OFFSET, green$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics green
     * }
     */
    public static void green(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, green$OFFSET, green$LAYOUT.byteSize());
    }

    private static final GroupLayout blue$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("blue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImageChannelStatistics blue
     * }
     */
    public static final GroupLayout blue$layout() {
        return blue$LAYOUT;
    }

    private static final long blue$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImageChannelStatistics blue
     * }
     */
    public static final long blue$offset() {
        return blue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics blue
     * }
     */
    public static MemorySegment blue(MemorySegment struct) {
        return struct.asSlice(blue$OFFSET, blue$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics blue
     * }
     */
    public static void blue(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, blue$OFFSET, blue$LAYOUT.byteSize());
    }

    private static final GroupLayout opacity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("opacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImageChannelStatistics opacity
     * }
     */
    public static final GroupLayout opacity$layout() {
        return opacity$LAYOUT;
    }

    private static final long opacity$OFFSET = 120;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImageChannelStatistics opacity
     * }
     */
    public static final long opacity$offset() {
        return opacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics opacity
     * }
     */
    public static MemorySegment opacity(MemorySegment struct) {
        return struct.asSlice(opacity$OFFSET, opacity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImageChannelStatistics opacity
     * }
     */
    public static void opacity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, opacity$OFFSET, opacity$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

