// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _Timer {
 *     double start;
 *     double stop;
 *     double total;
 * }
 * }
 */
public class _Timer {

    _Timer() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        magick_wand_h.C_DOUBLE.withName("start"),
        magick_wand_h.C_DOUBLE.withName("stop"),
        magick_wand_h.C_DOUBLE.withName("total")
    ).withName("_Timer");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble start$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double start
     * }
     */
    public static final OfDouble start$layout() {
        return start$LAYOUT;
    }

    private static final long start$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double start
     * }
     */
    public static final long start$offset() {
        return start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double start
     * }
     */
    public static double start(MemorySegment struct) {
        return struct.get(start$LAYOUT, start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double start
     * }
     */
    public static void start(MemorySegment struct, double fieldValue) {
        struct.set(start$LAYOUT, start$OFFSET, fieldValue);
    }

    private static final OfDouble stop$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("stop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double stop
     * }
     */
    public static final OfDouble stop$layout() {
        return stop$LAYOUT;
    }

    private static final long stop$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double stop
     * }
     */
    public static final long stop$offset() {
        return stop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double stop
     * }
     */
    public static double stop(MemorySegment struct) {
        return struct.get(stop$LAYOUT, stop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double stop
     * }
     */
    public static void stop(MemorySegment struct, double fieldValue) {
        struct.set(stop$LAYOUT, stop$OFFSET, fieldValue);
    }

    private static final OfDouble total$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("total"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double total
     * }
     */
    public static final OfDouble total$layout() {
        return total$LAYOUT;
    }

    private static final long total$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double total
     * }
     */
    public static final long total$offset() {
        return total$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double total
     * }
     */
    public static double total(MemorySegment struct) {
        return struct.get(total$LAYOUT, total$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double total
     * }
     */
    public static void total(MemorySegment struct, double fieldValue) {
        struct.set(total$LAYOUT, total$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

