// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _AffineMatrix {
 *     double sx;
 *     double rx;
 *     double ry;
 *     double sy;
 *     double tx;
 *     double ty;
 * } AffineMatrix
 * }
 */
public class AffineMatrix extends _AffineMatrix {

    AffineMatrix() {
        // Should not be called directly
    }
}

