// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _Ascii85Info {
 *     long offset;
 *     long line_break;
 *     magick_uint8_t buffer[10];
 * } Ascii85Info
 * }
 */
public class Ascii85Info extends _Ascii85Info {

    Ascii85Info() {
        // Should not be called directly
    }
}

