// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _ChromaticityInfo {
 *     PrimaryInfo red_primary;
 *     PrimaryInfo green_primary;
 *     PrimaryInfo blue_primary;
 *     PrimaryInfo white_point;
 * } ChromaticityInfo
 * }
 */
public class ChromaticityInfo extends _ChromaticityInfo {

    ChromaticityInfo() {
        // Should not be called directly
    }
}

