// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _CompositeOptions_t {
 *     double percent_brightness;
 *     double amount;
 *     double threshold;
 * } CompositeOptions_t
 * }
 */
public class CompositeOptions_t extends _CompositeOptions_t {

    CompositeOptions_t() {
        // Should not be called directly
    }
}

