// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _ErrorInfo {
 *     double mean_error_per_pixel;
 *     double normalized_mean_error;
 *     double normalized_maximum_error;
 * } ErrorInfo
 * }
 */
public class ErrorInfo extends _ErrorInfo {

    ErrorInfo() {
        // Should not be called directly
    }
}

