// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _ExportPixelAreaOptions {
 *     QuantumSampleType sample_type;
 *     double double_minvalue;
 *     double double_maxvalue;
 *     unsigned int grayscale_miniswhite;
 *     unsigned long pad_bytes;
 *     unsigned char pad_value;
 *     EndianType endian;
 *     unsigned long signature;
 * } ExportPixelAreaOptions
 * }
 */
public class ExportPixelAreaOptions extends _ExportPixelAreaOptions {

    ExportPixelAreaOptions() {
        // Should not be called directly
    }
}

