// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _GradientInfo {
 *     GradientType type;
 *     PixelPacket color;
 *     SegmentInfo stop;
 *     unsigned long length;
 *     SpreadMethod spread;
 *     unsigned long signature;
 *     struct _GradientInfo *previous;
 *     struct _GradientInfo *next;
 * } GradientInfo
 * }
 */
public class GradientInfo extends _GradientInfo {

    GradientInfo() {
        // Should not be called directly
    }
}

