// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _HistogramColorPacket {
 *     PixelPacket pixel;
 *     unsigned long count;
 * } HistogramColorPacket
 * }
 */
public class HistogramColorPacket extends _HistogramColorPacket {

    HistogramColorPacket() {
        // Should not be called directly
    }
}

