// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _ImageInfo {
 *     CompressionType compression;
 *     unsigned int temporary;
 *     unsigned int adjoin;
 *     unsigned int antialias;
 *     unsigned long subimage;
 *     unsigned long subrange;
 *     unsigned long depth;
 *     char *size;
 *     char *tile;
 *     char *page;
 *     InterlaceType interlace;
 *     EndianType endian;
 *     ResolutionType units;
 *     unsigned long quality;
 *     char *sampling_factor;
 *     char *server_name;
 *     char *font;
 *     char *texture;
 *     char *density;
 *     double pointsize;
 *     double fuzz;
 *     PixelPacket pen;
 *     PixelPacket background_color;
 *     PixelPacket border_color;
 *     PixelPacket matte_color;
 *     unsigned int dither;
 *     unsigned int monochrome;
 *     unsigned int progress;
 *     ColorspaceType colorspace;
 *     ImageType type;
 *     long group;
 *     unsigned int verbose;
 *     char *view;
 *     char *authenticate;
 *     void *client_data;
 *     FILE *file;
 *     char magick[2053];
 *     char filename[2053];
 *     _CacheInfoPtr_ cache;
 *     void *definitions;
 *     Image *attributes;
 *     unsigned int ping;
 *     PreviewType preview_type;
 *     unsigned int affirm;
 *     _BlobInfoPtr_ blob;
 *     size_t length;
 *     char unique[2053];
 *     char zero[2053];
 *     unsigned long signature;
 * } ImageInfo
 * }
 */
public class ImageInfo extends _ImageInfo {

    ImageInfo() {
        // Should not be called directly
    }
}

