// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _ImageStatistics {
 *     ImageChannelStatistics red;
 *     ImageChannelStatistics green;
 *     ImageChannelStatistics blue;
 *     ImageChannelStatistics opacity;
 * } ImageStatistics
 * }
 */
public class ImageStatistics extends _ImageStatistics {

    ImageStatistics() {
        // Should not be called directly
    }
}

