// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _ImportPixelAreaInfo {
 *     size_t bytes_imported;
 * } ImportPixelAreaInfo
 * }
 */
public class ImportPixelAreaInfo extends _ImportPixelAreaInfo {

    ImportPixelAreaInfo() {
        // Should not be called directly
    }
}

