// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _MagickInfo {
 *     struct _MagickInfo *next;
 *     struct _MagickInfo *previous;
 *     const char *name;
 *     const char *description;
 *     const char *note;
 *     const char *version;
 *     const char *module;
 *     DecoderHandler decoder;
 *     EncoderHandler encoder;
 *     MagickHandler magick;
 *     void *client_data;
 *     unsigned int adjoin;
 *     unsigned int raw;
 *     unsigned int stealth;
 *     unsigned int seekable_stream;
 *     unsigned int blob_support;
 *     unsigned int thread_support;
 *     CoderClass coder_class;
 *     ExtensionTreatment extension_treatment;
 *     unsigned long signature;
 * } MagickInfo
 * }
 */
public class MagickInfo extends _MagickInfo {

    MagickInfo() {
        // Should not be called directly
    }
}

