// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef unsigned int (*MonitorHandler)(const char *, const magick_int64_t, const magick_uint64_t, ExceptionInfo *)
 * }
 */
public class MonitorHandler {

    MonitorHandler() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment text, long quantum, long span, MemorySegment exception);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        magick_wand_h.C_INT,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_LONG,
        magick_wand_h.C_LONG,
        magick_wand_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = magick_wand_h.upcallHandle(MonitorHandler.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(MonitorHandler.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment text, long quantum, long span, MemorySegment exception) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, text, quantum, span, exception);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

