// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef unsigned int (*PixelIteratorTripleModifyCallback)(void *, const void *, const Image *, const PixelPacket *, const IndexPacket *, const Image *, const PixelPacket *, const IndexPacket *, Image *, PixelPacket *, IndexPacket *, const long, ExceptionInfo *)
 * }
 */
public class PixelIteratorTripleModifyCallback {

    PixelIteratorTripleModifyCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment mutable_data, MemorySegment immutable_data, MemorySegment source1_image, MemorySegment source1_pixels, MemorySegment source1_indexes, MemorySegment source2_image, MemorySegment source2_pixels, MemorySegment source2_indexes, MemorySegment update_image, MemorySegment update_pixels, MemorySegment update_indexes, long npixels, MemorySegment exception);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        magick_wand_h.C_INT,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_POINTER,
        magick_wand_h.C_LONG,
        magick_wand_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = magick_wand_h.upcallHandle(PixelIteratorTripleModifyCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(PixelIteratorTripleModifyCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment mutable_data, MemorySegment immutable_data, MemorySegment source1_image, MemorySegment source1_pixels, MemorySegment source1_indexes, MemorySegment source2_image, MemorySegment source2_pixels, MemorySegment source2_indexes, MemorySegment update_image, MemorySegment update_pixels, MemorySegment update_indexes, long npixels, MemorySegment exception) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, mutable_data, immutable_data, source1_image, source1_pixels, source1_indexes, source2_image, source2_pixels, source2_indexes, update_image, update_pixels, update_indexes, npixels, exception);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

