// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _PixelIteratorOptions {
 *     int max_threads;
 *     unsigned long signature;
 * } PixelIteratorOptions
 * }
 */
public class PixelIteratorOptions extends _PixelIteratorOptions {

    PixelIteratorOptions() {
        // Should not be called directly
    }
}

