// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _PrimaryInfo {
 *     double x;
 *     double y;
 *     double z;
 * } PrimaryInfo
 * }
 */
public class PrimaryInfo extends _PrimaryInfo {

    PrimaryInfo() {
        // Should not be called directly
    }
}

