// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _RectangleInfo {
 *     unsigned long width;
 *     unsigned long height;
 *     long x;
 *     long y;
 * } RectangleInfo
 * }
 */
public class RectangleInfo extends _RectangleInfo {

    RectangleInfo() {
        // Should not be called directly
    }
}

