// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _TimerInfo {
 *     Timer user;
 *     Timer elapsed;
 *     TimerState state;
 *     unsigned long signature;
 * } TimerInfo
 * }
 */
public class TimerInfo extends _TimerInfo {

    TimerInfo() {
        // Should not be called directly
    }
}

