// Generated by jextract

package magick;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _TypeInfo {
 *     char *path;
 *     char *name;
 *     char *description;
 *     char *family;
 *     StyleType style;
 *     StretchType stretch;
 *     unsigned long weight;
 *     char *encoding;
 *     char *foundry;
 *     char *format;
 *     char *metrics;
 *     char *glyphs;
 *     unsigned int stealth;
 *     unsigned long signature;
 *     struct _TypeInfo *previous;
 *     struct _TypeInfo *next;
 * } TypeInfo
 * }
 */
public class TypeInfo extends _TypeInfo {

    TypeInfo() {
        // Should not be called directly
    }
}

