// Generated by jextract

package org.mylib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Foo {
 *     struct {
 *         int baz;
 *     } bar;
 *     void (*cb)(void);
 * }
 * }
 */
public class Foo {

    Foo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Foo.bar.layout().withName("bar"),
        MemoryLayout.paddingLayout(4),
        mylib_h.C_POINTER.withName("cb")
    ).withName("Foo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * struct {
     *     int baz;
     * }
     * }
     */
    public static class bar {

        bar() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            mylib_h.C_INT.withName("baz")
        ).withName("$anon$38:5");

        /**
         * The layout of this struct
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final OfInt baz$LAYOUT = (OfInt)$LAYOUT.select(groupElement("baz"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int baz
         * }
         */
        public static final OfInt baz$layout() {
            return baz$LAYOUT;
        }

        private static final long baz$OFFSET = $LAYOUT.byteOffset(groupElement("baz"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int baz
         * }
         */
        public static final long baz$offset() {
            return baz$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int baz
         * }
         */
        public static int baz(MemorySegment struct) {
            return struct.get(baz$LAYOUT, baz$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int baz
         * }
         */
        public static void baz(MemorySegment struct, int fieldValue) {
            struct.set(baz$LAYOUT, baz$OFFSET, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this struct
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout bar$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("bar"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct {
     *     int baz;
     * } bar
     * }
     */
    public static final GroupLayout bar$layout() {
        return bar$LAYOUT;
    }

    private static final long bar$OFFSET = $LAYOUT.byteOffset(groupElement("bar"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct {
     *     int baz;
     * } bar
     * }
     */
    public static final long bar$offset() {
        return bar$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct {
     *     int baz;
     * } bar
     * }
     */
    public static MemorySegment bar(MemorySegment struct) {
        return struct.asSlice(bar$OFFSET, bar$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct {
     *     int baz;
     * } bar
     * }
     */
    public static void bar(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bar$OFFSET, bar$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * void (*cb)(void)
     * }
     */
    public final static class cb {

        private cb() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply();
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid();

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = mylib_h.upcallHandle(cb.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(cb.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr) {
            try {
                 DOWN$MH.invokeExact(funcPtr);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout cb$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*cb)(void)
     * }
     */
    public static final AddressLayout cb$layout() {
        return cb$LAYOUT;
    }

    private static final long cb$OFFSET = $LAYOUT.byteOffset(groupElement("cb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*cb)(void)
     * }
     */
    public static final long cb$offset() {
        return cb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*cb)(void)
     * }
     */
    public static MemorySegment cb(MemorySegment struct) {
        return struct.get(cb$LAYOUT, cb$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*cb)(void)
     * }
     */
    public static void cb(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cb$LAYOUT, cb$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

