// Generated by jextract

package org.mylib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class mylib_h extends mylib_h$shared {

    mylib_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int MY_MACRO = (int)42L;
    /**
     * {@snippet lang=c :
     * #define MY_MACRO 42
     * }
     */
    public static int MY_MACRO() {
        return MY_MACRO;
    }

    private static class foo {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            mylib_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("foo");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void foo(int x)
     * }
     */
    public static FunctionDescriptor foo$descriptor() {
        return foo.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void foo(int x)
     * }
     */
    public static MethodHandle foo$handle() {
        return foo.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void foo(int x)
     * }
     */
    public static MemorySegment foo$address() {
        return foo.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void foo(int x)
     * }
     */
    public static void foo(int x) {
        var mh$ = foo.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("foo", x);
            }
            mh$.invokeExact(x);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class bar$constants {
        public static final OfInt LAYOUT = mylib_h.C_INT;
        public static final MemorySegment SEGMENT = SYMBOL_LOOKUP.findOrThrow("bar").reinterpret(LAYOUT.byteSize());
    }

    /**
     * Layout for variable:
     * {@snippet lang=c :
     * int bar
     * }
     */
    public static OfInt bar$layout() {
        return bar$constants.LAYOUT;
    }

    /**
     * Segment for variable:
     * {@snippet lang=c :
     * int bar
     * }
     */
    public static MemorySegment bar$segment() {
        return bar$constants.SEGMENT;
    }

    /**
     * Getter for variable:
     * {@snippet lang=c :
     * int bar
     * }
     */
    public static int bar() {
        return bar$constants.SEGMENT.get(bar$constants.LAYOUT, 0L);
    }

    /**
     * Setter for variable:
     * {@snippet lang=c :
     * int bar
     * }
     */
    public static void bar(int varValue) {
        bar$constants.SEGMENT.set(bar$constants.LAYOUT, 0L, varValue);
    }
    private static final int A = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MY_ENUM.A = 0
     * }
     */
    public static int A() {
        return A;
    }
    private static final int B = (int)1L;
    /**
     * {@snippet lang=c :
     * enum MY_ENUM.B = 1
     * }
     */
    public static int B() {
        return B;
    }
    private static final int C = (int)2L;
    /**
     * {@snippet lang=c :
     * enum MY_ENUM.C = 2
     * }
     */
    public static int C() {
        return C;
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * void foo_variadic(int x, ...)
     * }
     */
    public static class foo_variadic {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.ofVoid(
                mylib_h.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("foo_variadic");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private foo_variadic(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * void foo_variadic(int x, ...)
         * }
         */
        public static foo_variadic makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new foo_variadic(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public void apply(int x, Object... x1) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("foo_variadic", x, x1);
                }
                 spreader.invokeExact(x, x1);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }
    /**
     * {@snippet lang=c :
     * typedef int MyInt
     * }
     */
    public static final OfInt MyInt = mylib_h.C_INT;

    private static class FOO_ARRAY$constants {
        public static final SequenceLayout LAYOUT = MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(5, mylib_h.C_INT));
        public static final MemorySegment SEGMENT = SYMBOL_LOOKUP.findOrThrow("FOO_ARRAY").reinterpret(LAYOUT.byteSize());
    public static final VarHandle HANDLE = LAYOUT.varHandle(sequenceElement(), sequenceElement());

        public static final long[] DIMS = { 3, 5 };
    }

    /**
     * Layout for variable:
     * {@snippet lang=c :
     * int FOO_ARRAY[3][5]
     * }
     */
    public static SequenceLayout FOO_ARRAY$layout() {
        return FOO_ARRAY$constants.LAYOUT;
    }

    /**
     * Dimensions for array variable:
     * {@snippet lang=c :
     * int FOO_ARRAY[3][5]
     * }
     */
    public static long[] FOO_ARRAY$dimensions() {
        return FOO_ARRAY$constants.DIMS;
    }

    /**
     * Getter for variable:
     * {@snippet lang=c :
     * int FOO_ARRAY[3][5]
     * }
     */
    public static MemorySegment FOO_ARRAY() {
        return FOO_ARRAY$constants.SEGMENT;
    }

    /**
     * Setter for variable:
     * {@snippet lang=c :
     * int FOO_ARRAY[3][5]
     * }
     */
    public static void FOO_ARRAY(MemorySegment varValue) {
        MemorySegment.copy(varValue, 0L, FOO_ARRAY$constants.SEGMENT, 0L, FOO_ARRAY$constants.LAYOUT.byteSize());
    }

    /**
     * Indexed getter for variable:
     * {@snippet lang=c :
     * int FOO_ARRAY[3][5]
     * }
     */
    public static int FOO_ARRAY(long index0, long index1) {
        return (int)FOO_ARRAY$constants.HANDLE.get(FOO_ARRAY$constants.SEGMENT, 0L, index0, index1);
    }

    /**
     * Indexed setter for variable:
     * {@snippet lang=c :
     * int FOO_ARRAY[3][5]
     * }
     */
    public static void FOO_ARRAY(long index0, long index1, int varValue) {
        FOO_ARRAY$constants.HANDLE.set(FOO_ARRAY$constants.SEGMENT, 0L, index0, index1, varValue);
    }
}

