// Generated by jextract

package org.mylib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct Point {
 *     int x;
 *     int y;
 * } MyPoint
 * }
 */
public class MyPoint extends Point {

    MyPoint() {
        // Should not be called directly
    }
}

